### ISSUE TITLE
Not possible to get DarkSky Api key anymore

### ISSUE THREAD

**Issue by jaalvarezvi** [hamvocke/spring-testing#13]
From what I see, unfortunately, it is not possible to get an API Key from DarkSky anymore. They are no longer accepting new signups. Any idea of how can we fix this issue? Thanks!

**Comment by hamvocke** [comment]
Thanks for getting this on my radar! Sounds like DarkSky's acquisition made them shut down their API first and foremost. Bummer.

Ultimately, the example in this codebase isn't really tied to using DarkSky's API at all - it's just about consuming _any_ API, DarkSky was just a neat real-world example.

I need some time to work through this to include a different API, write new contract tests, update readmes and blog posts and what not.

**Comment by psgg1981** [comment]
...or openweathermap.org ?

**Comment by hamvocke** [comment]
Sorry, this has taken me longer than it should have. I've just pushed some updates. The example code is now using openweathermap.org instead of darksky.net. Thanks @psgg1981 for the suggestion and thanks everyone else for getting this to my attention and helping figuring out a solution.
