### ISSUE TITLE
Add step to ReadMe for installing docker, if you haven't already done so

### ISSUE THREAD

**Issue by eyatzeck** [hamvocke/spring-testing#2]
Hi Ham, I love this reference instance.  I thought it was a nice challenge to try to figure out how to install and start docker on my laptop, but it might be nice to include the step in the readme!  ;-)  Cheers,

Elena

**Comment by hamvocke** [comment]
Adding that to the readme is a first start. Replacing the `startDatabase.sh` script with `docker-compose` might also be useful to get started easier.
